[project]
name = "migrations"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "psycopg[binary,pool]>=3.3.2",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.12.0",
    "sqlalchemy[asyncio,postgresql-asyncpg]>=2.0.45",
]

